process STAR {
    // Define the number of cpus to be used for this process
    label 'process_high'

    // Define the Docker image to be used for this process
    container 'ghcr.io/bf528/star:latest'

    // Put the output files in the results directory
    publishDir params.outdir, mode: 'copy'

    // The input is the reference genome and gtf file
    input:
    path(ref)
    path(gtf)

    // This is the index file generated by STAR using the reference and gtf files
    output:
    path "star_index_output/*", emit: index
    
    script:
    """
    mkdir -p star_index_output
    chmod +w star_index_output
    STAR --runThreadN $task.cpus --runMode genomeGenerate --genomeDir star_index_output --genomeFastaFiles $ref --sjdbGTFfile $gtf --sjdbOverhang 100
    """
}