
process STAR_ALIGNER {

    // Define the number of cpus to be used for this process
    label "process_high"

    // Define the Docker image to be used for this process
    container "ghcr.io/bf528/star:latest"

    // Put the output files in the results directory
    publishDir params.outdir, mode: "copy"

    // The input is reads 1 and 2 and the index file that was generated by STAR
    input:
    tuple val(sample_id), path(read1), path(read2)
    path(index)

    // This is the index file generated by STAR using the reference and gtf files
    output:
    tuple val(sample_id), path("${sample_id}.Aligned.sortedByCoord.out.bam"), emit: bam
    tuple val(sample_id), path("${sample_id}.Log.final.out"), emit: log
    
    script:
    """
    STAR --runThreadN $task.cpus \\
         --genomeDir $index \\
         --readFilesIn $read1 $read2 \\
         --readFilesCommand zcat \\
         --outFileNamePrefix ${sample_id}. \\
         --outSAMtype BAM SortedByCoordinate \\
         2> ${sample_id}.Log.final.out
    """
}